name: Deploy to Github Pages

on:
  push:
    branches: 'main'

  workflow_displatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8
      
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          pnpm run build
        
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'
      
  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4